set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'avakhov/vim-yaml'

Plugin 'https://github.com/altercation/vim-colors-solarized.git'
Plugin 'fatih/vim-go'
Plugin 'mutewinter/nginx.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'bling/vim-airline'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" ... EVERYTHING ELSE ...

" jsx and es6

let g:jsx_ext_required = 0

syntax on
filetype on
set synmaxcol=10000

" map F9 to toggle line numbers
nnoremap <F9> :<C-U>exe "set invnumber"<CR>
vnoremap <F9> :<C-U>exe "set invnumber"<CR>

"easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" map :Q! to quit
command! -bar -bang Q quit<bang>

" highlight .ipy files
au BufRead,BufNewFile *.ipy set filetype=python
" syntax highlighting - try harder
autocmd BufEnter * :syntax sync fromstart
let c_minlines=1000
syntax sync minlines=1000


"
" change indent depending on filetype
" -----------------------------------

" Default to 4 char tabs. Probably gets overridden.
set shiftwidth=4
set softtabstop=4

autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType coffeescript setlocal shiftwidth=2 tabstop=2
autocmd FileType xhtml setlocal shiftwidth=2 tabstop=2
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType htm setlocal shiftwidth=2 tabstop=2
autocmd FileType php setlocal shiftwidth=2 tabstop=2
autocmd FileType xml setlocal shiftwidth=2 tabstop=2
autocmd FileType ipython setlocal shiftwidth=4 tabstop=4
autocmd FileType ipy setlocal shiftwidth=4 tabstop=4
autocmd FileType python setlocal shiftwidth=4 tabstop=4
autocmd FileType c setlocal cindent
autocmd FileType h setlocal cindent

"dont ask me about changes when I switch buffers
"automatically set the file with changes as 'hidden'
set hidden

"highlight search terms
set hlsearch

"show search matches as you type
set incsearch

" This shows what you are typing as a command.  I love this!
set showcmd

" trying to get yy, D and P to work with system clipboard
set clipboard=unnamed

" Who doesn't like autoindent?
"set autoindent

" Spaces are better than a tab character
set expandtab
set smarttab

" display line numbers
set number

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" Enable use of the mouse for all modes
set mouse=n

" make backspace work like most other apps
set backspace=2

" Set the command window height to 2 lines, to avoid many cases of having to
" 'press <Enter> to continue'
set cmdheight=2

"always show status line (filename)
set ls=2

" Add the cool little dots for spaces while in Insert mode
set list
set listchars=tab:>.,trail:⋮,extends:#,nbsp:.

set background=dark
colorscheme solarized


" ************ Status Line *************

"set statusline=%t       "tail of the filename
"set statusline+=%=      "left/right separator
"set statusline+=%c,     "cursor column
"set statusline+=%l/%L   "cursor line/total lines
"set statusline+=\ %P    "percent through file

" ************************************

if $TMUX == ''
    set clipboard+=unnamed
else
    set clipboard=unnamed
endif
