#!/usr/bin/env bash

export PATH=~/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/lib:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.pyenv/bin:~/.local/bin:$PATH

# The primary requirement for using the dotfiles project
# is setting DOTFILES_DIR...
# https://github.com/samstav/dotfiles
export DOTFILES_DIR=${DOTFILES_DIR:-~/dotfiles}

echo '💙'

errcho() {
  printf "%s\n" "$@" 1>&2
}

errxit ()
{
  errcho "$@"
  exit 1
}


# shellcheck disable=SC2120
_err() {
  errcho $@
  if [ -n "${1:-}" ]; then
    _errmsg="⏩ Error at line ${1} of ${BASH_SOURCE:-${0}}"
    if [ -n "${2:-}" ]; then
      _errmsg="${_errmsg} in function '${2}'"
    fi
    errcho "${_errmsg}"
  fi
  errcho "⛔️ Script failed."
}

_sigint() {
  errcho "🍿 Script discontinued."
  exit 1
}

trap '_err ${LINENO} ${FUNCNAME:-}' ERR
trap '_sigint' SIGHUP SIGINT SIGTERM

if [ ! -d "${DOTFILES_DIR}" ]; then
  errcho 'dotfiles directory not found'
else
  source "${DOTFILES_DIR}/bash/dotfiles.sh"
  source "${DOTFILES_DIR}/bash/prompt.sh"
  source "${DOTFILES_DIR}/bash/ssh.sh"
  source "${DOTFILES_DIR}/homebrew/homebrew.sh"
  alias confpython="source ${DOTFILES_DIR}/lang/python/python.sh"
  source "${DOTFILES_DIR}/lang/node/node.sh"
  source "${DOTFILES_DIR}/lang/go/go.sh"
  alias confruby="source ${DOTFILES_DIR}/lang/ruby/ruby.sh"
  if [[ -f "${DOTFILES_DIR}/bash/history.sh" ]]; then
    source "${DOTFILES_DIR}/bash/history.sh"
  fi
  source "${DOTFILES_DIR}/bash/fzf.sh"
  if [[ $OSTYPE =~ "darwin" ]]; then
    source "${DOTFILES_DIR}/osx/osx.sh"
    source "${DOTFILES_DIR}/karabiner/karabiner.sh"
    source "${DOTFILES_DIR}/bash/asdf.sh"
    # Can't get iterm2_shell_integration to play
    # nicely with direnv, disabling for now :(
    #source "${DOTFILES_DIR}/term/iterm2.sh"
  fi
  # autocomplete scm, tmux
  for f in "${DOTFILES_DIR}"/autocomplete/*.bash; do
    # run ./bash/fetch_autocompleters.sh to fetch these
    source $f;
  done
  # direnv last
  source "${DOTFILES_DIR}/bash/direnv.sh"
  source "${DOTFILES_DIR}/bash/colors.sh"
  source "${DOTFILES_DIR}/bash/aliases.sh"
fi

# vim please
export VISUAL=vim
export EDITOR=vim
export GIT_EDITOR=vim
